### ISSUE TITLE
Add option for light brightness on advanced page?

### ISSUE THREAD

**Issue by rettigs** [rettigs/cs-senior-capstone#11]
Even though we can't currently do PWM for the lights, we should still probably have a slider or something to control light brightness on the advanced page.

**Comment by steelee** [comment]
Added stuff in commit 34d164ef183c165722e64f503029106b9da54aaa
Close the issue if it's enough, otherwise if we want to modify the queries or add a database entry let me know.

**Comment by rettigs** [comment]
Thanks!
