### ISSUE TITLE
Make rules not override manual settings for 2 hours

### ISSUE THREAD

**Issue by rettigs** [rettigs/cs-senior-capstone#14]
Plan: when toggling lights/groups, add current time + 2 hours to column in database and modify the run_queries function to not run the query for that light/group if that time is in the future.

If a group is manually overridden, all of its children should be as well.

**Comment by rettigs** [comment]
Overrides have been implemented, but the time is currently hardcoded to 60 seconds.  It needs to pull the time from the database still.

**Comment by steelee** [comment]
Fixed: c7d4b617f2f67f6dc81555a4658128999cfd952a
We now pull the timer from the database.
