### ISSUE TITLE
Make lights default to "OR" mode

### ISSUE THREAD

**Issue by rettigs** [rettigs/cs-senior-capstone#16]
Currently, new lights/groups default to "OWN" mode, meaning they are not controlled by their parent in any capacity, so settings rules on groups does nothing by default.  This is bad.  The default should either be "PARENT", "AND", or "OR" mode so that the parent group's rules will affect lights.

PARENT is bad because then light rules do nothing by default.

This means it's between AND and OR.  I think OR would be better since it's harder for users to mess up; a poor set of rules ANDed together can create queries that will never be true, e.g. a light turns on on Friday, and the parent turns on on Sunday, but it can never be both Friday and Sunday at once, so the light never turns on.  Thoughts?

**Comment by mdiller** [comment]
Query properly defaults to OR as of commit b6bde56ff953b61764899d45e695f7cc199cef59, but the logic is not fully implemented yet.

**Comment by rettigs** [comment]
The default fill state on the advanced page is now correct, but the default query for lights and such is still blank, which gets interpreted by run_queries as 'False', so this is still an issue.  We either need to populate the querydata columns when lights are created or set some default in run_queries.

**Comment by rettigs** [comment]
I just made blank queries default to "parent".  If they get edited, the "OR" mode will automatically get applied.
