### ISSUE TITLE
Make sure light statuses are updated on front page when rules change them

### ISSUE THREAD

**Issue by rettigs** [rettigs/cs-senior-capstone#17]
Since the front page is supposed to indicate the state of lights/groups, we need to make sure that when rules are evaluated that change the state of lights, the front page is updated without the user needing the refresh the page.

We also need to make it update if it's changed by other methods, e.g. from other web pages.  It also needs to be updated when names change, groups are created/deleted, or when lights/groups are reordered.

We should figure out whether we want the client to pull updates or have pushes from the server.

**Comment by steelee** [comment]
Added a pull request
