### ISSUE TITLE
Groups don't display properly when parent group is deleted

### ISSUE THREAD

**Issue by rettigs** [rettigs/cs-senior-capstone#3]
When a group contains other groups and the parent group is deleted, the child group's elements appear under the new parent group rather than their original parent.  Refreshing the page displays everything correctly.

E.g.

- Group A
  - Group B (x)
    - Group C
      - Light D
      - Light E
      - Light F

When Group B is deleted, it shows:

- Group A
  - Group C
  - Light D
  - Light E
  - Light F

It should be (and is when refreshed):

- Group A
  - Group C
    - Light D
    - Light E
    - Light F

**Comment by mdiller** [comment]
resolved by 8213bb756aec16e726caea799a74e4e2ff7fda3c
