### ISSUE TITLE
Make advanced page load current settings into the page

### ISSUE THREAD

**Issue by rettigs** [rettigs/cs-senior-capstone#6]
Currently, the advanced page always starts with the same checkboxes checked, etc.  It should be loaded with the current settings.

**Comment by mdiller** [comment]
Resolved by 536c97484b295640a9472aed7c04bf2374b7ce06.

**Comment by rettigs** [comment]
Reopening because this is currently incomplete; the advanced query checkbox is checked and the toggle early/late/randomize are not loaded (although they haven't been added to the querydata yet anyway, so I don't blame you).  I'll update this ticket once the dependency issue has been fixed.

**Comment by rettigs** [comment]
@mdiller You're good to finish this up now.

**Comment by mdiller** [comment]
Resolved by 19854a71178e3a9b156ebfa72bb1ab071da4334e

**Comment by rettigs** [comment]
Thanks!
