### ISSUE TITLE
"All Lights" does not function properly

### ISSUE THREAD

**Issue by steelee** [rettigs/cs-senior-capstone#9]
The large parent group "All Lights" returns this error when flipping the switch on and off:
`UnboundLocalError: local variable 'result' referenced before assignment`
Need to examine the changes and the parent references to find out why this issue is happening.

**Comment by mdiller** [comment]
Resolved by commit 0edf62c1e80c572494f905d48d493cd651741624. The result variable was not assigned to a value for groups containing no lights.
